name: Compile if needed

on:
  push:

jobs:
  check-formatting:
    if: (github.repository_owner != 'xaroth' || (github.ref_name != 'main' && github.ref_type == 'branch')) && github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Send slack notification
        # We add this if to ensure this doesn't run on forks.
        # If you really want to run this on your own fork, configure the required secrets.
        if: env.SLACK_BOT_TOKEN && env.SLACK_CHANNEL_ID
        continue-on-error: true
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
        uses: ./
        with:
          slack-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          message-summary: Checking if ${{ github.ref_name }} needs an updated build

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Get yarn cache dir
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Fetch the yarn cache
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn --prefer-offline --frozen-lockfile

      - name: Run the build
        run: yarn build

      - name: Check for modified files
        id: is-modified
        run: echo ::set-output name=modified::$(if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then echo "true"; else echo "false"; fi)

      - name: Push changes if there are any
        if: steps.is-modified.outputs.modified == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am "Automatically fix formatting" --author="${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          git push
